subtom_src_dir = '/home/dmorado/opt/subTOM/src';
tom_src_dir = '/home/dmorado/Builds/tom';
toolbox_src_dir = '/home/dmorado/opt/MATLAB/R2020b/toolbox';

include_filtrans = fullfile(tom_src_dir, 'Filtrans');
include_geom = fullfile(tom_src_dir, 'Geom');
include_iofun = fullfile(tom_src_dir, 'IOfun');
include_sptrans = fullfile(tom_src_dir, 'Sptrans');

include_utils = fullfile(subtom_src_dir, 'utils');

include_stats = fullfile(toolbox_src_dir, 'stats', 'stats');

start_dir = cd(fullfile(subtom_src_dir, 'MOTL'));
mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_cat_motls.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_cat_motls.sh
!mv subtom_cat_motls ../../bin/MOTL/subtom_cat_motls

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_clean_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_clean_motl.sh
!mv subtom_clean_motl ../../bin/MOTL/subtom_clean_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_compare_motls.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_compare_motls.sh
!mv subtom_compare_motls ../../bin/MOTL/subtom_compare_motls

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_even_odd_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_even_odd_motl.sh
!mv subtom_even_odd_motl ../../bin/MOTL/subtom_even_odd_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_random_subset_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_random_subset_motl.sh
!mv subtom_random_subset_motl ../../bin/MOTL/subtom_random_subset_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_renumber_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_renumber_motl.sh
!mv subtom_renumber_motl ../../bin/MOTL/subtom_renumber_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_rotx_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_rotx_motl.sh
!mv subtom_rotx_motl ../../bin/MOTL/subtom_rotx_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_scale_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_scale_motl.sh
!mv subtom_scale_motl ../../bin/MOTL/subtom_scale_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_seed_positions.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_seed_positions.sh
!mv subtom_seed_positions ../../bin/MOTL/subtom_seed_positions

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_split_motl_by_row.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_split_motl_by_row.sh
!mv subtom_split_motl_by_row ../../bin/MOTL/subtom_split_motl_by_row

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_transform_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_transform_motl.sh
!mv subtom_transform_motl ../../bin/MOTL/subtom_transform_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_unclass_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_unclass_motl.sh
!mv subtom_unclass_motl ../../bin/MOTL/subtom_unclass_motl

cd(fullfile(subtom_src_dir, 'alignment'));
mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_extract_noise.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_extract_noise.sh
!mv subtom_extract_noise ../../bin/alignment/subtom_extract_noise

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_extract_subtomograms.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_extract_subtomograms.sh
!mv subtom_extract_subtomograms ../../bin/alignment/subtom_extract_subtomograms

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_sums.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_sums.sh
!mv subtom_parallel_sums ../../bin/alignment/subtom_parallel_sums

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_scan_angles_exact.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_scan_angles_exact.sh
!mv subtom_scan_angles_exact ../../bin/alignment/subtom_scan_angles_exact

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_weighted_average.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_weighted_average.sh
!mv subtom_weighted_average ../../bin/alignment/subtom_weighted_average

cd(fullfile(subtom_src_dir, 'analysis'));
mcc('-m', '-v', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_maskcorrected_fsc.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_maskcorrected_fsc.sh
!mv subtom_maskcorrected_fsc ../../bin/analysis/subtom_maskcorrected_fsc

cd(fullfile(subtom_src_dir, 'analysis', 'b_factor_by_subsets'));
mcc('-m', '-v', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_maskcorrected_fsc_bfactor.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_maskcorrected_fsc_bfactor.sh
!mv subtom_maskcorrected_fsc_bfactor ../../../bin/analysis/b_factor_by_subsets/subtom_maskcorrected_fsc_bfactor

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_sums_bfactor.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_sums_bfactor.sh
!mv subtom_parallel_sums_bfactor ../../../bin/analysis/b_factor_by_subsets/subtom_parallel_sums_bfactor

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_weighted_average_bfactor.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_weighted_average_bfactor.sh
!mv subtom_weighted_average_bfactor ../../../bin/analysis/b_factor_by_subsets/subtom_weighted_average_bfactor

cd(fullfile(subtom_src_dir, 'classification', 'general'));
mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    '-I', include_stats, ...
    'subtom_cluster.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_cluster.sh
!mv subtom_cluster ../../../bin/classification/general/subtom_cluster

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_prealign.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_prealign.sh
!mv subtom_parallel_prealign ../../../bin/classification/general/subtom_parallel_prealign

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_sums_cls.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_sums_cls.sh
!mv subtom_parallel_sums_cls ../../../bin/classification/general/subtom_parallel_sums_cls

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_scan_angles_exact_refs.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_scan_angles_exact_refs.sh
!mv subtom_scan_angles_exact_refs ../../../bin/classification/general/subtom_scan_angles_exact_refs

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_weighted_average_cls.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_weighted_average_cls.sh
!mv subtom_weighted_average_cls ../../../bin/classification/general/subtom_weighted_average_cls

cd(fullfile(subtom_src_dir, 'classification', 'msa'));
mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_eigenvolumes_msa.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_eigenvolumes_msa.sh
!mv subtom_eigenvolumes_msa ../../../bin/classification/msa/subtom_eigenvolumes_msa

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_join_eigencoeffs_msa.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_join_eigencoeffs_msa.sh
!mv subtom_join_eigencoeffs_msa ../../../bin/classification/msa/subtom_join_eigencoeffs_msa

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_join_xmatrix.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_join_xmatrix.sh
!mv subtom_join_xmatrix ../../../bin/classification/msa/subtom_join_xmatrix

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_eigencoeffs_msa.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_eigencoeffs_msa.sh
!mv subtom_parallel_eigencoeffs_msa ../../../bin/classification/msa/subtom_parallel_eigencoeffs_msa

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_xmatrix_msa.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_xmatrix_msa.sh
!mv subtom_parallel_xmatrix_msa ../../../bin/classification/msa/subtom_parallel_xmatrix_msa

cd(fullfile(subtom_src_dir, 'classification', 'multiref'));
mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_compare_motls_multiref.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_compare_motls_multiref.sh
!mv subtom_compare_motls_multiref ../../../bin/classification/multiref/subtom_compare_motls_multiref

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_rand_class_motl.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_rand_class_motl.sh
!mv subtom_rand_class_motl ../../../bin/classification/multiref/subtom_rand_class_motl

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_scan_angles_exact_multiref.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_scan_angles_exact_multiref.sh
!mv subtom_scan_angles_exact_multiref ../../../bin/classification/multiref/subtom_scan_angles_exact_multiref

cd(fullfile(subtom_src_dir, 'classification', 'pca'));
mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_eigs.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_eigs.sh
!mv subtom_eigs ../../../bin/classification/pca/subtom_eigs

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_join_ccmatrix.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_join_ccmatrix.sh
!mv subtom_join_ccmatrix ../../../bin/classification/pca/subtom_join_ccmatrix

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_join_eigencoeffs_pca.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_join_eigencoeffs_pca.sh
!mv subtom_join_eigencoeffs_pca ../../../bin/classification/pca/subtom_join_eigencoeffs_pca

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_join_eigenvolumes.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_join_eigenvolumes.sh
!mv subtom_join_eigenvolumes ../../../bin/classification/pca/subtom_join_eigenvolumes

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_ccmatrix.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_ccmatrix.sh
!mv subtom_parallel_ccmatrix ../../../bin/classification/pca/subtom_parallel_ccmatrix

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_eigencoeffs_pca.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_eigencoeffs_pca.sh
!mv subtom_parallel_eigencoeffs_pca ../../../bin/classification/pca/subtom_parallel_eigencoeffs_pca

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_eigenvolumes.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_eigenvolumes.sh
!mv subtom_parallel_eigenvolumes ../../../bin/classification/pca/subtom_parallel_eigenvolumes

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_xmatrix_pca.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_xmatrix_pca.sh
!mv subtom_parallel_xmatrix_pca ../../../bin/classification/pca/subtom_parallel_xmatrix_pca

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_prepare_ccmatrix.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_prepare_ccmatrix.sh
!mv subtom_prepare_ccmatrix ../../../bin/classification/pca/subtom_prepare_ccmatrix

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_svds.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_svds.sh
!mv subtom_svds ../../../bin/classification/pca/subtom_svds

cd(fullfile(subtom_src_dir, 'classification', 'wmd'));
mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_eigenvolumes_wmd.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_eigenvolumes_wmd.sh
!mv subtom_eigenvolumes_wmd ../../../bin/classification/wmd/subtom_eigenvolumes_wmd

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_join_coeffs.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_join_coeffs.sh
!mv subtom_join_coeffs ../../../bin/classification/wmd/subtom_join_coeffs

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_join_dmatrix.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_join_dmatrix.sh
!mv subtom_join_dmatrix ../../../bin/classification/wmd/subtom_join_dmatrix

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_coeffs.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_coeffs.sh
!mv subtom_parallel_coeffs ../../../bin/classification/wmd/subtom_parallel_coeffs

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_parallel_dmatrix.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_parallel_dmatrix.sh
!mv subtom_parallel_dmatrix ../../../bin/classification/wmd/subtom_parallel_dmatrix

cd(fullfile(subtom_src_dir, 'utils'));
mcc('-m', '-v', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_bandpass.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_bandpass.sh
!mv subtom_bandpass ../../bin/utils/subtom_bandpass

mcc('-m', '-v', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_plot_filter.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_plot_filter.sh
!mv subtom_plot_filter ../../bin/utils/subtom_plot_filter

mcc('-m', '-v', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_plot_scanned_angles.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_plot_scanned_angles.sh
!mv subtom_plot_scanned_angles ../../bin/utils/subtom_plot_scanned_angles

mcc('-m', '-v', ...
    '-R', '-nojvm', ...
    '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-R', '-nosplash', ...
    '-N', ...
    '-I', include_filtrans, ...
    '-I', include_geom, ...
    '-I', include_iofun, ...
    '-I', include_sptrans, ...
    '-I', include_utils, ...
    'subtom_shape.m');

!rm mccExcludedFiles.log
!rm requiredMCRProducts.txt
!rm readme.txt
!rm run_subtom_shape.sh
!mv subtom_shape ../../bin/utils/subtom_shape

cd(start_dir);
